
name: Run Orchestrator

on:
  workflow_dispatch:
    inputs:
      goal:
        description: 'Goal for the orchestrator'
        required: true
        default: 'Launch beta for EU SMB founders'
      post_filename:
        description: 'Output filename for the LinkedIn post (default: post_linkedin.md)'
        required: false
        default: 'post_linkedin.md'

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install openai anthropic
      - name: Run orchestrator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LLM_RESEARCHER: openai
          LLM_STRATEGIST: anthropic
          LLM_CONTENT_PLANNER: openai
          LLM_COPYWRITER: openai
          AUTO_APPROVE: '1'
          BUDGET_EUR: '8'
          POST_FILENAME: ${{ github.event.inputs.post_filename }}
        run: |
          export PYTHONPATH=.
          GOAL="${{ github.event.inputs.goal }}"
          python app/main.py --goal "${GOAL}"
      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A out
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[bot] Orchestrator outputs [skip ci]"
            git push
          fi
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-out-${{ github.run_id }}
          path: out/**
          if-no-files-found: warn
