name: Run Orchestrator

on:
  workflow_dispatch:
    inputs:
      goal:
        description: 'Goal for the orchestrator'
        required: true
        default: 'Launch beta for EU SMB founders'

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install openai anthropic
      - name: Run orchestrator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LLM_RESEARCHER: openai
          LLM_STRATEGIST: anthropic
          LLM_CONTENT_PLANNER: openai
          LLM_COPYWRITER: openai
          AUTO_APPROVE: '1'
          BUDGET_EUR: '8'
        run: |
          export PYTHONPATH=.
          GOAL="${{ github.event.inputs.goal }}"
          python app/main.py --goal "${GOAL}"
      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A out
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[bot] Orchestrator outputs [skip ci]"
            git push
          fi
